name = "MakieExtras"
uuid = "298d008f-8aeb-4429-988e-255aefbbbef8"
authors = ["Patrick Bouffard <bouffard@eecs.berkeley.edu> and contributors"]
version = "0.0.1-DEV"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
