name = "MakieExtras"
uuid = "298d008f-8aeb-4429-988e-255aefbbbef8"
authors = ["Patrick Bouffard <bouffard@eecs.berkeley.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
